spring.application.name=SistemaInternoBibliotecaEscolar

spring.datasource.url=jdbc:postgresql://localhost:5432/Sistema_Interno_de_Biblioteca_Escolar
spring.datasource.driverClassName=org.postgresql.Driver

spring.datasource.username=postgres

spring.datasource.password=postgresRui2026


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
