spring.application.name=SistemaInternoBibliotecaEscolar

# --- CONFIGURAÇÃO DO POSTGRESQL ---
# Altere "nome_da_sua_base_de_dados" para o nome que deu à base de dados no pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/Sistema_Interno_de_Biblioteca_Escolar
spring.datasource.driverClassName=org.postgresql.Driver

# Mantenha "postgres" se for o utilizador padrão
spring.datasource.username=postgres
# Coloque aqui a sua password de acesso ao pgAdmin
spring.datasource.password=postgresRui2026

# --- JPA / HIBERNATE ---
# 'validate' serve para verificar se as futuras classes Java batem certo com o pgAdmin sem alterar nada
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
